# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f40614367d9a074a2059bde9c283fea4cdbffa70e7c718f8e846bc6a1e025d140fe5dddd7bcbb43aee1bb65b14235be958d7030a5830fdc9908b2b9297d6aa7

test:
  secret_key_base: 2b46f1a5fe0b9ea582f52604b474ac4db4d73aaf1a34d6df18151e59be07bc2b54bb8403d1462fe08855ec7039992d8d91ea061548e94e8fa86df429bd93d2d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
